# Generated by Django 5.1.3 on 2024-12-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food',
            new_name='food_consumed',
        ),
    ]
