# Generated by Django 5.1.3 on 2024-12-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_food_consume_food_consumed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='protien',
            new_name='protein',
        ),
    ]
